db:
  image: postgres:15
  container_name: db
  restart: always
  environment:
    POSTGRES_DB: transport
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - "5432:5432"
  volumes:
    - db_data:/var/lib/postgresql/data