server.port=${PORT:8082}

spring.datasource.url=jdbc:postgresql://db:5432/transport
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.open-in-view=false


